---
title: "joining all the traits together"
output: html_document
---
```{r}
library(here)
library(dplyr)
```



```{r}
#read in all the trait data

flower_colour <- read.csv(here("processed trait data", "flower colour.csv"))

fruit_size <- read.csv(here("processed trait data", "fruit size.csv"))

seed_length <- read.csv(here("processed trait data", "seed length.csv"))

seed_mass <- read.csv(here("processed trait data", "seed mass.csv"))

size_at_rep_maturity <- read.csv(here("processed trait data", "size at reproductive maturity.csv"))

wood_density <- read.csv(here("processed trait data", "wood density.csv"))

dispersal_syndrome <- read.csv(here("processed trait data", "dispersal syndrome.csv"))

```

```{r}
merged_traits <- flower_colour %>%
  full_join(fruit_size,           by = c("binomial_name", "family", "genus", "species")) %>%
  full_join(seed_length,          by = c("binomial_name", "family", "genus", "species")) %>%
  full_join(seed_mass,            by = c("binomial_name", "family", "genus", "species")) %>%
  full_join(size_at_rep_maturity, by = c("binomial_name", "family", "genus", "species")) %>%
  full_join(wood_density,         by = c("binomial_name", "family", "genus", "species")) %>%
  full_join(dispersal_syndrome,         by = c("binomial_name", "family", "genus", "species")) %>%
  select (binomial_name, family, genus, species, species_origin.x, logging_status.x, history_at_IF_site.x, history_at_CP_site.x, flower_colour, dispersal_syndrome, fruit_size_mm, fruit_size_min_mm, seed_length_mm, mean_dry_seed_mass_mg, mean_wood_density_g_cm_3, flowering_at_size_class ) %>%
  distinct()

#check if any species occur more than once - yes, they do
merged_traits %>%
  count(binomial_name) %>%
  filter(n > 1)
```

```{r}
#put NA values where there are blank spaces in flower_colour column
merged_traits$flower_colour[trimws(merged_traits$flower_colour) == ""] <- NA

write.csv(merged_traits, file = here("processed trait data", "all traits database.csv"), row.names = FALSE)
```

```{r}
#count the number of species that have at least one trait value
merged_traits %>%
  filter(if_any(
    c(flower_colour, dispersal_syndrome, fruit_size_mm, fruit_size_min_mm,
      seed_length_mm, mean_dry_seed_mass_mg, mean_wood_density_g_cm_3,
      flowering_at_size_class),
    ~ !is.na(.)
  )) %>%
  distinct(binomial_name) %>%
  count()

#to see the number of species that have two or more trait values

merged_traits %>%
  rowwise() %>%
  mutate(non_na_count = sum(!is.na(across(c(
    flower_colour, dispersal_syndrome, fruit_size_mm, fruit_size_min_mm,
    seed_length_mm, mean_dry_seed_mass_mg, mean_wood_density_g_cm_3,
    flowering_at_size_class
  ))))) %>%
  ungroup() %>%
  filter(non_na_count >= 2) %>%
  distinct(binomial_name) %>%
  count()
```

```{r}
#count the number of species that have data for each trait
#e.g shown here for flower colour
length(unique(merged_traits$binomial_name[!is.na(merged_traits$flower_colour)]))

```


