---
title: "accessing plant traits"
output: html_document 
---

```{r}
library(here)#for telling R where my working directory is
library(BIEN)#contains the BIEN dataset
library(dplyr)#for manipulating dataframes
library(stringr)#for working with strings
library(tidyverse)#for data wrangling
library(ggplot2)
library(viridisLite)
library(viridis)

```

LIST OF SPECIES IN DANUM
```{r}
#read in the 'final species list corrected and cleaned'
species_list <- read.csv(here("species list data", "final species list corrected and cleaned.csv"))


#create a new column with corrected binomial name of each species
species_list$binomial_name <- paste(species_list$genus, species_list$species)

#final species list of distinct species in each site, as created in the 'creating the final species list' .Rmd
final_species_list <- read.csv(here("species list data", "final species list.csv"))
```


```{r}
#now to correct the error from creating the final species list, I need to merge species_list and final_species_list 
corrected_species_list <- left_join(species_list, final_species_list, by = c("original_binomial_name" = "binomial_name")) %>%
  select(binomial_name, family, genus, species, history_at_IF_site, history_at_CP_site, species_origin.y, logging_status.y) %>%
  rename(species_origin = species_origin.y, logging_status = logging_status.y)

species_list <- corrected_species_list

write.csv(species_list, file = here("species list data", "species list.csv"), row.names = FALSE)

```


TRY DATABASE
```{r}
#read in the raw TRY data
TRY_data_raw <- read.delim(here("raw trait data", "TRY", "TRY data.txt"))
```

```{r}
#I want to create a separate dataset for each trait, so that the data is easier to handle
# List of TraitIDs you want to filter
trait_ids <- c(207, 28, 26, 239, 919, 917, 4, 3684, 335)

# Create a list to store each subset as a separate data frame
separated_datasets <- list()

# Loop through each TraitID and filter the dataset
for (trait_id in trait_ids) {
  dataset_name <- paste0("TraitID_", trait_id)
  separated_datasets[[dataset_name]] <- TRY_data_raw %>%
    filter(TraitID == trait_id)
}

#create an object for each trait dataset

flower_colour_TRY <- separated_datasets$TraitID_207
#14 records on flower colour, worth working with 

seed_dispersal_syndrome_TRY <- separated_datasets$TraitID_28
#321 entries, worth working with 

seed_dry_mass_TRY <- separated_datasets$TraitID_26
#656 records, worth working with 

seed_width_TRY <- separated_datasets$TraitID_239
#1 records - discard

fruit_dry_mass_TRY <- separated_datasets$TraitID_919
#only 4 different species - not really worth it

fruit_width_TRY <- separated_datasets$TraitID_917
#1 record - discard

wood_density_TRY <- separated_datasets$TraitID_4
#1581 records, worth working with 

crown_elevation_TRY <- separated_datasets$TraitID_3684
#0 records, discard

reproductive_phenology_TRY <- separated_datasets$TraitID_335
#only 5 different species
```


THE BIEN TRAITS DATASET
```{r}
#exploring the BIEN database
#use vignette("BIEN_tutorial") for instructions on how to extract data from the database

#this gives a list of all the traits that this database has information on - 54 different traits.
BIEN_trait_list <- BIEN_trait_list()

#make a vector of my 753 species
list_sp <- species_list$binomial_name 
  
#now do some cleanup of the species list, necessary to use the list in BIEN
list_sp_cleaned <- list_sp %>%
  iconv(from = "", to = "UTF-8", sub = "byte") %>% #force encoding to UTF-8 and replace non-convertible characters
  gsub(pattern = "\u00a0", replacement = " ", .) %>% #replace non-breaking space (\u00a0)
  trimws() #trim whitespace
 
``` 

SORTING DATA BY TRAIT

1) FLOWER COLOUR 

```{r}
#looking at flower colour
# I can't use in BIEN_trait_mean because flower colour is not a numerical variable - it is categorical.
flower_colour_BIEN <- BIEN_trait_traitbyspecies(species = list_sp_cleaned, trait = "flower color")
#out of my 753 species, only 3 have flower colour data in BIEN
```

```{r}
#flower trait data from Trethowan et al 2024
trethowan_data <- read.csv(here("raw trait data", "Flower_Trait_Data.csv"))

#merge the species list and the trethowan datasets together
flower_colour_trethowan <- left_join(species_list, trethowan_data, by = c("binomial_name" = "species")) %>%
  select(binomial_name, family.x, genus, species, species_origin, logging_status, corolla_colour, reference) %>% 
  distinct()

#Merge flower_traits from Trethowan with flower_colour from TRY
flower_colour_merged <- left_join(flower_colour_trethowan, flower_colour_TRY, by = c("binomial_name" = "AccSpeciesName")) %>%
  select(binomial_name, family.x, genus, species, species_origin, logging_status, corolla_colour, reference, OrigValueStr, Reference)

#now I want to combine corolla_colour and OrigValueStr into one column called flower_colour, and combined reference and Reference into one column called reference
flower_colour_merged <- left_join(flower_colour_trethowan, flower_colour_TRY, by = c("binomial_name" = "AccSpeciesName")) %>%
  mutate(
    flower_colour = coalesce(corolla_colour, OrigValueStr),
    reference = coalesce(reference, Reference)
  ) %>%
  select(binomial_name, family.x, genus, species, species_origin, logging_status, flower_colour, reference) %>%
  rename(family = family.x)

#If there is more than one flower colour listed for a single species, I want to list them
flower_colour_final <- flower_colour_merged %>%
  group_by(binomial_name, family, genus, species, species_origin, logging_status) %>%
  summarise(
    flower_colour = str_c(unique(flower_colour[!is.na(flower_colour)]), collapse = ", "),
    reference = str_c(unique(reference[!is.na(reference)]), collapse = ", "),
    .groups = "drop")%>%
  mutate(reference = if_else(flower_colour == "", NA_character_, reference)) %>%
  rename(flower_colour_reference = reference)

#there is no point adding in flower colour form BIEN, because this only had flower colour for three species, all of which are now covered by either Trethowan or TRY.
#so far, this is the final dataset on flower colour - to get more I think I will have to manually look by species in books.

#save this dataset as a csv
write.csv(flower_colour_final, file = here("processed trait data", "flower colour.csv"), row.names = FALSE)

```

2) FRUIT SIZE

```{r}
#data on fruit size from Trethowan et al 2023
fruit_size_data <- read.csv(here("raw trait data", "figshare_fruit_data.csv"))

#merge the species list and the fruit size datasets together
fruit_size <- left_join(species_list, fruit_size_data, by = c("binomial_name" = "species")) %>%
  select(binomial_name, family, genus, species, species_origin, logging_status, fruit_size_mm, fruit_size_min_mm, reference) %>%
  distinct() %>%
  rename(fruit_size_reference = reference)

write.csv(fruit_size, file = here("processed trait data", "fruit size.csv"), row.names = FALSE)

```



3) SEED MASS
```{r}
#Take seed_dry_mass_TRY and tidy it up:
#select just the columns I want
#rename some columns
#take the mean of each seed mass for each species
#remember this is 1000 seed mass
seed_dry_mass_TRY_clean <- seed_dry_mass_TRY %>%
  select(AccSpeciesName, TraitName, StdValue, UnitName, Reference) %>%
  rename(dry_seed_mass_mg = StdValue, binomial_name = AccSpeciesName, reference = Reference) %>%
  group_by(binomial_name) %>%
  summarise(mean_dry_seed_mass_mg_TRY = round(mean(dry_seed_mass_mg, na.rm = TRUE), 2))
  
#add back in the references - idk why but I couldn't do this within the pipe
seed_dry_mass_TRY_clean <- left_join(seed_dry_mass_TRY_clean, seed_dry_mass_TRY, by = c("binomial_name" = "AccSpeciesName"))

#select just the columns I want
seed_dry_mass_TRY_clean <-  seed_dry_mass_TRY_clean %>%
  select(binomial_name, mean_dry_seed_mass_mg_TRY, Reference) %>%
  distinct() %>%
  group_by(binomial_name, mean_dry_seed_mass_mg_TRY) %>%
  summarise(Reference = str_c(unique(Reference[!is.na(Reference)]), collapse = ", "),
    .groups = "drop")
    
#merge species_list and seed_dry_mass_TRY_clean
merged_seed_mass <- left_join(species_list, seed_dry_mass_TRY_clean, by = c("binomial_name" = "binomial_name")) %>%
  select(binomial_name, family, genus, species, history_at_IF_site, history_at_CP_site, species_origin, logging_status, mean_dry_seed_mass_mg_TRY, Reference) %>%
  distinct()

```

```{r}
#SEED MASS from BIEN
#BIEN_trait_mean estimates species mean trait values for a given trait, using Genus or Family level data where species level data is absent
average_seed_mass_BIEN = BIEN_trait_mean(species = list_sp_cleaned, trait = "seed mass") 

average_seed_mass_BIEN <- average_seed_mass_BIEN %>%
  rename(mean_dry_seed_mass_BIEN = mean_value, binomial_name = species) %>%
  mutate(reference = "BIEN") %>%
  select(binomial_name, mean_dry_seed_mass_BIEN, level_used, reference)

#this assigns seed mass to all 753 species. It produces a dataframe which tells you the mean seed mass, the level used (family, genus or species) and the sample size used to produce that mean.

#BIEN_trait_traitby species extracts entries that conatin the specified species and traits. So this extracts the records only for the species that match exactly. If a species does not match, then it does not produce an estimate based on Genus or Family level
#seed_mass_by_species <- BIEN_trait_traitbyspecies(species = list_sp_cleaned, trait = "seed mass")
  
```

```{r}

#now I want to merge the seed mass from BIEN and from TRY
#PROBLEM: some of the same species occur in BIEN and in TRY, the problem is that they appear to have wildly different values, e.g
#Artocarpus elasticus has a seed mass of 150mg in TRY but 2682mg in BIEN
#maybe this is because the estimate in BIEN is based on genus or family level approximation
#so I dont think genus or family level approximations are necessarily very accurate at all
#
#I want to add in the BIEN data, but in a way that if there is already existing data in merged_seed_mass_TRY, i keep that data and I do not replace it.

final_seed_mass <- merged_seed_mass %>%
  left_join(average_seed_mass_BIEN, by = c("binomial_name")) %>%
  group_by(binomial_name, family, genus, species, species_origin, logging_status, history_at_IF_site, history_at_CP_site, level_used, reference, Reference) %>%
  summarise(
    mean_dry_seed_mass_mg = coalesce(mean_dry_seed_mass_mg_TRY, as.numeric(mean_dry_seed_mass_BIEN)),
    .groups = "drop"
  ) %>%
  mutate(
    reference = coalesce(Reference, reference)
  ) %>%
  rename(reference_seed_mass = reference) %>%
  select(-Reference)


#save as a csv file
write.csv(final_seed_mass, file = here("processed trait data", "seed mass.csv"), row.names = FALSE)


```




4) SEED SIZE
```{r}
#looking at seed size size
average_seed_length = BIEN_trait_mean(species = list_sp_cleaned, trait = "seed length")


#merge BIEN data with species list
merged_seed_length <- left_join(species_list, average_seed_length, by = c("binomial_name" = "species")) %>%
  select(binomial_name, family, genus, species, history_at_IF_site, history_at_CP_site, species_origin, logging_status, mean_value) %>%
  rename(seed_length_mm = mean_value) %>%
  mutate(seed_length_mm = as.numeric(seed_length_mm),
         reference = "BIEN")

#save as a csv file
write.csv(merged_seed_length, file = here("processed trait data", "seed length.csv"), row.names = FALSE)

```





5) WOOD DENSITIES
```{r}
#wood densities from the global wood density database (WDD)
wood_densities_raw <- read.csv(here("raw trait data", "GlobalWoodDensityDatabase.csv"))

#WDD stands for Wood Density Database
wood_densities_WDD <- left_join(species_list, wood_densities_raw, by = c("binomial_name" = "Binomial")) %>%
  rename(wood_density_g_cm_3 = Wood.density..g.cm.3...oven.dry.mass.fresh.volume) %>%
  select(binomial_name, wood_density_g_cm_3) %>%
  group_by(binomial_name) %>%
  summarise(mean_wood_density_g_cm_3 = round(mean(wood_density_g_cm_3, na.rm = TRUE), 2)) %>%
  filter(!is.nan(mean_wood_density_g_cm_3)) %>%
  mutate(reference = "WDD")

#wood densities from TRY
wood_density_TRY_clean <- wood_density_TRY %>%
  select(AccSpeciesName, StdValue) %>%
  rename(wood_density_g_cm_3 = StdValue, binomial_name = AccSpeciesName) %>%
  group_by(binomial_name) %>%
  summarise(mean_wood_density_g_cm_3 = round(mean(wood_density_g_cm_3, na.rm = TRUE), 2)) %>%
  filter(!is.nan(mean_wood_density_g_cm_3)) %>%
  mutate(reference = "TRY")

#join WDD and TRY datasets with the species_list
df_list <- list(species_list, wood_densities_WDD, wood_density_TRY_clean)

merged_wood_densities <- reduce(df_list, left_join, by = "binomial_name") %>%
  rename(mean_wood_density_g_cm_3_WDD = mean_wood_density_g_cm_3.x,
         mean_wood_density_g_cm_3_TRY = mean_wood_density_g_cm_3.y,
         reference_WDD = reference.x,
         reference_TRY = reference.y)

#now, i want to join mean_wood_density_g_cm_3_WDD and mean_wood_density_g_cm_3_TRY columns together. if there is a value in both, take the mean of both columns.
merged_wood_densities <- merged_wood_densities %>%
  mutate(
    mean_wood_density_g_cm_3 = case_when(
      !is.na(mean_wood_density_g_cm_3_WDD) & !is.na(mean_wood_density_g_cm_3_TRY) ~ 
        round((mean_wood_density_g_cm_3_WDD + mean_wood_density_g_cm_3_TRY) / 2, 2),
      !is.na(mean_wood_density_g_cm_3_WDD) ~ mean_wood_density_g_cm_3_WDD,
      !is.na(mean_wood_density_g_cm_3_TRY) ~ mean_wood_density_g_cm_3_TRY,
      TRUE ~ NA_real_
    )
  ) %>%
  group_by(binomial_name, family, genus, species, mean_wood_density_g_cm_3, species_origin, logging_status, history_at_IF_site, history_at_CP_site) %>%
  summarise(
    reference_wood_density = str_c(na.omit(c(unique(reference_WDD), unique(reference_TRY))), collapse = ", "),
    .groups = "drop"
  )

#now save as a csv file
#save as a csv file
write.csv(merged_wood_densities, file = here("processed trait data", "wood density.csv"), row.names = FALSE)

```

```{r}
merged_wood_densities <- merged_wood_densities %>%
  mutate(
    logged = if_else(logging_status %in% c("logged", "both"), 1, 0),
    unlogged = if_else(logging_status %in% c("unlogged", "both"), 1, 0)
  )
```




6) TALLO - TREE HEIGHT, CROWN RADIUS, STEM DIAMETER
```{r}
#Tallo (tree height)
tallo <- read.csv(here("trait data", "Tallo.csv"))


tree_height <- left_join(species_list, tallo, by = c("binomial_name" = "species")) %>%
  select(binomial_name, family.x, genus.x, species, stem_diameter_cm, height_m, crown_radius_m, species_origin, logging_status) %>%
  group_by(binomial_name) %>%
  summarise(
    mean_stem_diameter_cm = round(mean(stem_diameter_cm, na.rm = TRUE), 2),
    mean_height_m = round(mean(height_m, na.rm = TRUE), 2),
    mean_crown_radius_m = round(mean(crown_radius_m, na.rm = TRUE), 2),
    family = first(family.x),
    genus = first(genus.x),
    species = first(species),
    species_origin = first(species_origin),
    logging_status = first(logging_status),
    .groups = "drop"  # optional: drops the grouping afterwards
  ) %>%
  filter(!is.nan(mean_stem_diameter_cm))           
          
```

```{r}
#now I can plot the data
#are the species in the logged areas shorter?

ggplot(tree_height, aes(x = logging_status, y = mean_height_m)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6, color = "blue") +
  labs(
    title = "tree height",
    x = "Logging Status",
    y = "Mean tree height (m)"
  ) +
  theme_minimal()

#again, the issue is that there are too few species that are unique to logged sites
```

```{r}
ggplot(tree_height, aes(x = logging_status, y = mean_stem_diameter_cm)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6, color = "blue") +
  labs(
    title = "stem diameter",
    x = "Logging Status",
    y = "stem diameter cm"
  ) +
  theme_minimal()
```

```{r}
ggplot(tree_height, aes(x = logging_status, y = mean_crown_radius_m)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6, color = "blue") +
  labs(
    title = "mean crown radius (m)",
    x = "Logging Status",
    y = "Mean crown radius"
  ) +
  theme_minimal()

```

6) DISPERSAL SYNDROME
```{r}
unique(seed_dispersal_syndrome_TRY$AccSpeciesName)
```




