---
title: "exploring family-level estimates"
output: html_document
---

```{r}
library(here)
library(dplyr)
library(ggplot2)
library(viridis)
```

```{r}
seed_mass <- read.csv(here("processed trait data", "seed mass.csv"))

seed_length <- read.csv(here("processed trait data", "seed length.csv"))

all_traits_database <- read.csv(here("processed trait data", "all traits database.csv"))
```

```{r}
#see how many species have species, genus and family level estimates
seed_mass %>%
  group_by(level_used) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

seed_length %>%
  group_by(level_used) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

```

```{r}
#see how many species have seed mass only, seed length only, both, or neither
all_traits_database %>%
  mutate(
    data_category = case_when(
      !is.na(seed_length_mm) & !is.na(mean_dry_seed_mass_mg) ~ "Both",
      !is.na(seed_length_mm) &  is.na(mean_dry_seed_mass_mg) ~ "Seed length only",
       is.na(seed_length_mm) & !is.na(mean_dry_seed_mass_mg) ~ "Seed mass only",
       is.na(seed_length_mm) &  is.na(mean_dry_seed_mass_mg) ~ "Neither"
    )
  ) %>%
  count(data_category)
```


```{r}

#now I want to filter out so I am only looking at genus and species level estimates
seed_mass_genus <- seed_mass %>%
  filter(level_used %in% c("Genus", "Species"))

#i want to calculate the 10 most common families, with genus or species level estimates
top_families <- seed_mass %>%
  count(family, sort = TRUE) %>%
  slice_head(n = 15) %>%
  pull(family)


# Filter dataset to only include these top families
seed_mass_top <- seed_mass_genus %>%
  filter(family %in% top_families)

```

```{r}
# make a plot
ggplot(seed_mass_top, aes(x = mean_dry_seed_mass_mg,  # all points share same x-position
                          y = family,
                          color = family)) +
  geom_point() +
  scale_color_viridis(discrete = TRUE) +
  scale_x_log10() +
  labs(
    title = "species and genus-level estimates of seed mass",
    x = "log mean dry seed mass (mg)",
       y = "",
       color = "Family") +
  theme_minimal() +
  theme(legend.position = "none")
  
```


```{r}
#now i wan to add in the family-level estimate of seed mass on top
#filter out the seed mass dataset so that I have just family level estimates, and one row per family
seed_mass_family <- seed_mass %>%
  filter(level_used %in% c("Family")) %>%
  select(family, level_used, mean_dry_seed_mass_mg, reference_seed_mass) %>%
  distinct()

#now filter to only include the 15 top families counted above
seed_mass_top_family <- seed_mass_family %>%
  filter(family %in% top_families)

```

```{r}
# make a plot
ggplot(seed_mass_top, aes(x = mean_dry_seed_mass_mg,  
                          y = family,
                          color = family)) +
  geom_point(size = 3.0) + 
  geom_point(data = seed_mass_top_family, 
             aes(x = mean_dry_seed_mass_mg, y = family),
             color = "red", shape = 23, fill = "red", size = 3.5) +
  scale_color_viridis_d(option = "viridis") +
  labs(
    title = "",
    x = "1000 dry seed mass (mg)",
       y = "",
       color = "Family") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 14),     
    axis.title = element_text(size = 16),
    legend.position = "none")

```

```{r}
seed_mass_top

seed_mass_top_family_proc = seed_mass_top_family %>% 
  select(family, mean_dry_seed_mass_mg) %>% 
  rename(mean_dry_seed_mass_mg_family = mean_dry_seed_mass_mg) %>% 
  group_by(family) %>% 
  summarise(mean_dry_seed_mass_mg_family = mean(mean_dry_seed_mass_mg_family, na.rm = T))

(seed_mass_comparison = seed_mass_top %>% 
  left_join(seed_mass_top_family_proc, by = 'family') %>% 
    mutate(distance_abs = abs(mean_dry_seed_mass_mg_family - mean_dry_seed_mass_mg)) %>% 
  group_by(family) %>% 
    summarise(mean_distance_abs = mean(distance_abs, na.rm = TRUE)))

(seed_mass_comparison_rel = seed_mass_comparison %>% 
    left_join(seed_mass_top_family_proc, by = 'family') %>% 
    mutate(rel_distance = mean_distance_abs/mean_dry_seed_mass_mg_family)
)

```






```{r}
all_traits_database <- read.csv(here("processed trait data", "all traits database.csv"))

all_traits_database <- all_traits_database %>%
  mutate(log_seed_mass = log(mean_dry_seed_mass_mg))
```

```{r}
ggplot(all_traits_database, aes(x = mean_dry_seed_mass_mg, y = seed_length_mm)) +
  geom_point() 
```

```{r}
ggplot(all_traits_database, aes(x = log_seed_mass, y = seed_length_mm)) +
  geom_point() +
  labs(
    title = "",
    x = "log dry seed mass (mg)",
       y = "seed length (mm)",
       color = "Family") +
  annotate("text", 
           x = 6.5, y = 35,          # adjust position to fit your data
           label = expression(R^2 == 0.34),
           size = 5) +
  theme_minimal()
```


```{r}
#do a simple correlation

cor(all_traits_database$log_seed_mass,
    all_traits_database$seed_length_mm,
    use = "complete.obs")^2

```

```{r}
#now try a linear model

seed_model <- lm(seed_length_mm ~ log_seed_mass, data = all_traits_database)

summary(seed_model)
```
```{r}
ggplot(all_traits_database, aes(x = log_seed_mass, y = seed_length_mm)) +
  geom_point(size = 3.0) +
  geom_smooth(method = lm, size = 1.0) +
  labs(
    title = "",
    x = "log dry seed mass (mg)",
       y = "seed length (mm)",
       color = "Family") +
  annotate("text", 
           x = 6.5, y = 35,          # adjust position to fit your data
           label = expression(R^2 == 0.34),
           size = 7) +
  theme_minimal()+
  theme(
    axis.text = element_text(size = 18),       # axis tick labels
    axis.title = element_text(size = 20)       # axis titles
  )
```


PLOTTING THE 71 SPECIES LEVEL ESTIMATES

```{r}
#now for each species I want its species-level estimate, genus level estimate, and family level estimate

#filter out the seed mass dataset so that I have just family level estimates, and one row per family
seed_mass_family <- seed_mass %>%
  filter(level_used %in% c("Family")) %>%
  select(family, mean_dry_seed_mass_mg) %>%
  rename(family_level_seed_mass = mean_dry_seed_mass_mg) %>%
  distinct()


#filter out to just get the species level estimates
seed_mass_species <- seed_mass %>%
  filter(level_used %in% c("Species")) %>%
  select(binomial_name, family,genus, mean_dry_seed_mass_mg) %>%
  rename(species_level_seed_mass = mean_dry_seed_mass_mg) %>%
  distinct()

#filter out to just get the species level estimates
seed_mass_genus <- seed_mass %>%
  filter(level_used %in% c("Genus")) %>%
  select(binomial_name, family, genus, level_used, mean_dry_seed_mass_mg) %>%
  rename(genus_level_seed_mass = mean_dry_seed_mass_mg) %>%
  distinct()

#join species and genus datasets together
species_and_genus <- seed_mass_species %>%
  left_join(seed_mass_genus, by = "genus") %>%
  select(binomial_name.x, family.x, genus, species_level_seed_mass, genus_level_seed_mass) %>%
  rename(family = family.x) %>%
  distinct()

#now add in the family level estimates
all_levels <- species_and_genus %>%
  left_join(seed_mass_family, by = "family") %>%
  distinct()

```

```{r}
#now plot the 71 species level estimates against their genus level estimates
lims <- range(log(c(all_levels$genus_level_seed_mass, 
                    all_levels$species_level_seed_mass)), na.rm = TRUE)
#
ggplot(all_levels, aes(x = log(genus_level_seed_mass), y = log(species_level_seed_mass))) +
  geom_point(size = 3.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", size = 1.0) +
  labs(
    title = "",
    x = "Genus",
       y = "Species") +
  annotate("text", 
           x = 4, y = 8,      
           label = expression(R^2 == 0.616),
           size = 7) +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 18),       # axis tick labels
    axis.title = element_text(size = 20)       # axis titles
  ) +
  xlim(lims) + ylim(lims)


#now calculate the root mean square error
all_levels %>%
  summarise(rmse = sqrt(mean((species_level_seed_mass - genus_level_seed_mass)^2, na.rm = TRUE))) 

#calculate the R-squared

cor(all_levels$genus_level_seed_mass,
    all_levels$species_level_seed_mass,
    use = "complete.obs")^2
#R-squared is 0.616
```






```{r}
#now plot the 71 species level estimates against their genus level estimates
ggplot(all_levels, aes(x = log(family_level_seed_mass), y = log(species_level_seed_mass), colour = family)) +
  geom_point(size = 3.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", size = 1.0)  +
  labs(
    title = "",
    x = "Family",
       y = "Species") +
  annotate("text", 
           x = 4.0, y = 8,      
           label = expression(R^2 == 0.023),
           size = 7) +
  theme_minimal() +
  scale_colour_viridis_d(option = "viridis") + 
  guides(colour = "none") +
  theme(
    axis.text = element_text(size = 18),       # axis tick labels
    axis.title = element_text(size = 20)       # axis titles
  ) +
  xlim(lims) + ylim(lims)


#now calculate the root mean square error
all_levels %>%
  summarise(rmse = sqrt(mean((species_level_seed_mass - family_level_seed_mass)^2, na.rm = TRUE)))

cor(all_levels$species_level_seed_mass,
    all_levels$family_level_seed_mass,
    use = "complete.obs")^2
#R-squared is 0.0228 = 
```

PLOTTING THE 236 GENUS VALUES
```{r}
#join the genus_level estimates with the family-level estimates
genus_and_family <- seed_mass_genus %>%
  left_join(seed_mass_family, by = "family") %>%
  distinct()

#now plot the genus level estimates against the family level estimates
ggplot(genus_and_family, aes(x = log(genus_level_seed_mass), y = log(family_level_seed_mass))) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")  +
  labs(
    title = "",
    x = "log genus level seed mass",
       y = "log family level seed mass") +
  annotate("text", 
           x = 6.5, y = 10,      
           label = expression(RMSE == 3878.8),
           size = 5) +
  theme_minimal()


#calculate the root mean square error
genus_and_family %>%
  summarise(rmse = sqrt(mean((genus_level_seed_mass - family_level_seed_mass)^2, na.rm = TRUE)))

```




