---
title: "plant traits database"
output: html_document
---

**DOCUMENT SETUP**

```{r}
library(here)#for telling R where my working directory is
library(BIEN)#contains the BIEN dataset
library(dplyr)#for manipulating dataframes
library(stringr)#for working with strings
```

note: I couldn't install BIEN because my R would not install the package RPostgreSQL. This code seemed to fix the problem: install.packages("RPostgreSQL", type = "binary")

**CREATING THE DANUM SPECIES LIST**

```{r}
#read in the list of unlogged tree species from the 50ha site
unlogged_species <- read.csv(here("Danum_spp_list_unlogged.csv"))

#create a new column with the full binomial latin name of each species
unlogged_species$binomial_name <- paste(unlogged_species$Genus, unlogged_species$Species)

#create a dataframe of just the species names of unlogged trees.
unlogged_species_list <- unlogged_species %>% 
  select(binomial_name, Family, Genus, Species) %>% #selects just the columns we want
  mutate(logging_status = "unlogged") %>% #adds a new column called logging_status, and fills it with 'unlogged'
  mutate(species_origin = "50ha") %>% #adds a column called species_origin, and fills it with '50ha'
  distinct(binomial_name, .keep_all=TRUE) #removes any duplicates from the list, based only on binomial_name

```

```{r}
#read in the dataset of logged tree species from the CP site
logged_species <- read.csv(here("DanumRevised_35Plots_FullPlotData_Trees_2020_edit_4.11.csv"))

#create a column with the full binomial latin name of each species
logged_species$binomial_name <- paste(logged_species$Genus, logged_species$Species)

#make a list of distinct species names from the logged trees.
logged_species_list <- logged_species %>%
  select(binomial_name, Family, Genus, Species) %>% 
  mutate(logging_status = "logged") %>%
  mutate(species_origin = "CP") %>%
  distinct(binomial_name, .keep_all = TRUE) #removes duplicates from the list of species

#make the Family listed in title case, rather than in all capital letters.  
logged_species_list$Family <- str_to_title(str_to_lower(logged_species_list$Family))

```

```{r}
#now combine the logged_species_list and the unlogged_species_list together
#bind_rows() combines the two dataframes together
#group_by() groups according to binomial name
#summarize() - if a species appears more than once in the list, it is assigned "both" as its logging status, otherwise, it is assigned the logging_status that it already had when the dataframes were separate
#ungroup() ungroups the data

combined_species_list <- bind_rows(logged_species_list, unlogged_species_list) %>%
  group_by(binomial_name) %>%
  summarize(
    Family = first(Family),
    Genus = first(Genus),
    Species = first(Species),
    species_origin = toString(sort(unique(species_origin))),#makes the species origin column
    logging_status = if (n_distinct(logging_status) > 1) "both" else first(logging_status),
    .groups = "drop"
  )

#save the combined_species_list as a csv file
write.csv(combined_species_list, file = "combined species list.csv", row.names = FALSE)

```

```{r}
#adding in lists of species from actively restored or naturally regenerated areas
#read in the data of the species found in the INFORSUS (logged) site
INDFORSUS_data <- read.csv("mature_data_RH(in).csv")

#read in the data on their restoration status
INDFORSUS_restoration_status_data <- read.csv("2018_2019Seedling_RH(Plot_Info).csv")

#now join the two datasets together
INDFORSUS_species_list <- INDFORSUS_data %>%
  left_join(INDFORSUS_restoration_status_data, by = "station", relationship = "many-to-many")%>% #join the two datasets together according to their station
  select(family, genus, species, history)%>% #select only the columns that we are interested in 
  distinct() %>% #remove rows that have the same information in every single column
  mutate(binomial_name = paste(genus, species, sep = " ")) %>% # add in a column with the binomial_name
  mutate(species_origin = "IF") %>%
  mutate(logging_status = "logged") %>%
  rename( #change the names of the columns so that they are written with capital letters
    Family = family,
    Genus = genus,
    Species = species
  )

```

```{r}
#this code is to check how many unique species there are in the INDFORSUS_data dataset
print(unique(INDFORSUS_data$species_code))
#this dataset includes shorea fagetiana. hence has 22 unique species
```

```{r}
#this code is to check how manu unique species there are in the InDFORSUS_species_list dataset
print(unique(INDFORSUS_species_list$binomial_name))
#this has both shorea fageutiana and shorea faguentiana, hence has 23 unique species
```



```{r}
#now I want to join the  final_species list and the INDFORSUS species lists together. In both datasets there is a column called binomial_name which contains the name of the species. I want to join the two datasets according to the binomial_name.
#
#
final_species_list <- bind_rows(combined_species_list, INDFORSUS_species_list) %>%
  group_by(binomial_name) %>%
  summarize(
    Family = first(Family),
    Genus = first(Genus),
    Species = first(Species),
    history = toString(unique(history)),
    species_origin = toString(sort(unique(species_origin))),#makes the species origin column
    logging_status = if (n_distinct(logging_status) > 1) "both" else first(logging_status),
    .groups = "drop")%>%
  filter(!is.na(Family)) #removes the last row which is full of NAs. specifically, where the family is NA.

#save the final_species_list as a .csv file
write.csv(final_species_list, file = "final species list.csv", row.names = FALSE)

```

####################################################################

**ADDING IN THE PLANT TRAIT DATASETS**

```{r}
#read in the plant trait datasets
#flower trait data
flower_traits <- read.csv(here("Flower_Trait_Data.csv"))

#Tallo
tallo <- read.csv(here("Tallo.csv"))

#wood densities
wood_densities <- read.csv(here("GlobalWoodDensityDatabase.csv"))
```

```{r}
#filtering out the flower_traits dataset, to only look at the 754 species that appear in the final_species_list 

#in the flower_traits dataset, change the column name from species to binomial_name
flower_traits <- flower_traits %>%
  rename(binomial_name = species)


# Filter flower_traits to only include species in final_species_list
filtered_flower_traits <- flower_traits %>%
  semi_join(final_species_list, by = "binomial_name")

#this filtered_flower_traits dataframe includes 50 species, meaning that there are 50 species in the flower_traits dataset that also appear in the unlogged_species dataset. This, of course, does not take into account that there might be alternative names for the same plant.
```

```{r}
#exploring the BIEN database
#use vignette("BIEN_tutorial") for instructions on how to extract data from the database
#this gives a list of all the traits that this database has information on - 55 different traits.
BIEN_trait_list <- BIEN_trait_list()
#I will need to work out how to extract the traits for all the species I am interested in

#to look at all observations of flower color:
BIEN_flower_colour <- BIEN_trait_trait(trait = "flower color")
#this shows that there are around 3400 species for which there is data on flower colour

#
```
